config:
  NB_USERS: 20
  NB_POSTS: 50

shared:
  user_id[[NB_USERS]]: UNIQUE[int]
  post_id[[NB_POSTS]]: UNIQUE[int]

tables:
  users[[NB_USERS]]:
    user_id: [[user_id]]
    name: NAME
    age: CHOOSE[[18-65]]
    email: str
    location: LOCATION
    theme: THEME
    language: LANGUAGE
    joined_date: str
    active: bool

  posts[[NB_POSTS]]:
    post_id: [[post_id]]
    user_id: [[user_id]]
    title: POST_TITLE
    tags: POST_TAGS[3]
    content: str
    published: bool

  user_permissions:
    user_id: [[user_id]]
    permissions: PERMISSIONS[n]
    granted_date: str