name: "toy-api-v1"
description: "Toy API (v1): Different endpoint structure"
port: 1234

routes:
  # Different endpoint structure to test custom route mapping
  - route: "/user-permissions/<user_id>"
    methods: ["GET"]
    response: "user_permissions"

  - route: "/users/<user_id>"
    methods: ["GET"]
    response: "user_detail"

  - route: "/profiles/<user_id>"
    methods: ["GET"]
    response: "user_profile"

  # Additional routes for testing
  - route: "/users"
    methods: ["GET"]
    response: "user_list"

  - route: "/users/<user_id>/settings"
    methods: ["GET"]
    response: "user_settings"

  - route: "/users/<user_id>/delete"
    methods: ["DELETE"]
    response: "user_detail"

  - route: "/health"
    methods: ["GET"]
    response: "health_check"